# Generated by Django 5.2.6 on 2025-09-26 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(help_text='The core Django User object.', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GoogleAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_id', models.CharField(help_text='Unique Google identifier.', max_length=255, unique=True)),
                ('access_token', models.TextField(blank=True, help_text='OAuth access token.')),
                ('refresh_token', models.TextField(blank=True, help_text='OAuth refresh token.')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_account', to='planningAgent.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CalendarEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('MEET', 'Meeting'), ('WORK', 'Work'), ('GYM', 'Gym/Exercise'), ('MEAL', 'Meal'), ('SLEEP', 'Sleep'), ('VAC', 'Vacation/Time Off'), ('OTHR', 'Other')], max_length=5)),
                ('title', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_entries', to='planningAgent.userprofile')),
            ],
            options={
                'verbose_name_plural': 'Calendar Entries',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='AvailabilityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_week', models.DateField(help_text='The Monday date of the week being analyzed.')),
                ('end_week', models.DateField(help_text='The Sunday date of the week being analyzed.')),
                ('total_hours', models.DecimalField(decimal_places=2, default=168, max_digits=5)),
                ('total_available_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('availability_ratio', models.DecimalField(decimal_places=3, help_text='Ratio (0.0 to 1.0).', max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='planningAgent.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='AvailabilityHourlyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(help_text='0=Monday, 6=Sunday')),
                ('hour_of_day', models.PositiveSmallIntegerField(help_text='0-23')),
                ('is_available', models.BooleanField(default=False)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_details', to='planningAgent.availabilityreport')),
            ],
            options={
                'ordering': ['day_of_week', 'hour_of_day'],
                'unique_together': {('report', 'day_of_week', 'hour_of_day')},
            },
        ),
    ]
